[theme]
primaryColor = "#F63366"  # Cor dos bot√µes e foco (Mude para a cor da sua marca)
backgroundColor = "#FFFFFF" # Fundo geral
secondaryBackgroundColor = "#F0F2F6" # Fundo da sidebar e inputs
textColor = "#262730"
font = "sans serif"

[server]
runOnSave = true